shortplay:
  jpa:
    shard:
      master:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            default_batch_fetch_size: 300
        open-in-view: false
