package com.mashup.shorts.consts

const val CATEGORY_WEIGHT_ONE = 1.0
const val CATEGORY_WEIGHT_ONE_QUARTER = 1.25
const val CATEGORY_WEIGHT_ONE_HALF = 1.5
const val CATEGORY_WEIGHT_ONE_HALF_QUARTER = 1.75
const val CATEGORY_WEIGHT_TWO = 2.0
const val CATEGORY_WEIGHT_TWO_HALF = 2.0
const val CATEGORY_WEIGHT_TWO_HALF_QUARTER = 2.75
const val CATEGORY_WEIGHT_THREE = 3.0

const val TITLE_WEIGHT = 2.0
const val CONTENT_WEIGHT = 1.0
