name: Shorts API Deploy with Gradle

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - feature/*
      - refactor/*
      - fix/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Execute Gradle Jib
        run: ./gradlew :shorts-api:jib -Dimage=${IMAGE} -Dtag=${TAG}
        env:
          IMAGE: shorts/shorts-api
          TAG: ${{ steps.version.outputs.version }}
