name: Shorts API Deploy with Gradle

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - feature/*
      - refactor/*
      - fix/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Version
        id: version
        run: |
          VERSION=${VERSIONING}-${{ github.run_id }}
          echo "::set-output name=version::${VERSION}"
        env:
          VERSIONING: ${{ github.event.inputs.version }}
      - name: Execute Gradle Jib
        run: ./gradlew :shorts-api:jib -Dimage=${IMAGE} -Dtag=${TAG}
        env:
          IMAGE: shorts/shorts-api
          TAG: v${{ steps.get_version.outputs.version }}
