name: Shorts API Deploy with Gradle

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - feature/*
      - refactor/*
      - fix/*

env:
  JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Version
        id: version
        run: |
          VERSION=${VERSIONING}-${{ github.run_id }}
          echo "::set-output name=version::${VERSION}"
        env:
          VERSIONING: ${{ github.event.inputs.version }}

      - name: Execute Gradle Jib
        run: ./gradlew :shorts-api:jib -Dimage=${IMAGE} -Dtag=${TAG}
        env:
          IMAGE: wjdrbs96/shorts
          TAG: v${{ steps.get_version.outputs.version }}

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: "+09:00"

      - name: deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: shorts
          environment_name: shorts-prod
          version_label: shorts-${{steps.current-time.outputs.formattedTime}}
          deployment_package: ./Dockerrun.aws.json
          wait_for_environment_recovery: 300
