name: SeeYouAgain-Spring CD with EB

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
          application_name: seeyouagain-spring-eb-app
          environment_name: seeyouagain-spring-eb-env
          version-label: "app-${{ github.sha }}"
          package: "build/libs/*.jar"
